# Generated by Django 6.0.4 on 2026-05-05 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('specialization', models.CharField(max_length=150, verbose_name='Спеціалізація')),
                ('experience_years', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стаж (років)')),
            ],
            options={
                'verbose_name': 'Лікар',
                'verbose_name_plural': 'Лікарі',
                'ordering': ['-experience_years', 'full_name'],
            },
        ),
    ]
